language: python
python: [2.7, 3.4, 3.5, 3.6, 3.7]
install:
- pip install tox-travis
script:
- tox
- '[[ "$TRAVIS_TAG" = "" ]] || [[ "$TRAVIS_TAG" = "$(python setup.py --version)" ]]'
- |
  if git show --format=%B --quiet "${TRAVIS_PULL_REQUEST_SHA:-${TRAVIS_TAG:-${TRAVIS_COMMIT}}}" \
     | grep '\[changelog skip\]' > /dev/null; then
    echo "Skip changelog checker..."
  elif [[ "$TRAVIS_TAG" != "" ]]; then
    ! grep -i "to be released" CHANGES.md
  else
    [[ "$TRAVIS_COMMIT_RANGE" = "" ]] || \
    [[ "$(git diff --name-only "$TRAVIS_COMMIT_RANGE" | grep CHANGES\.rst)" != "" ]]
  fi
